# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12VxV7rbBfqSi_bjOojPbyZRWxFIg9060
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/annex1.csv")

item = df["Item Code"].to_numpy()
print(item)

item = df["Item Name"].to_numpy()
print(item)

Category = df["Category Code"].to_numpy()
print(Category)

Category = df["Category Name"].to_numpy()
print(Category)



sales = [2500, 3000, 4000, 3500, 5000]

total_sales = sum(sales)
average_sales = total_sales / len(sales)

print("Total Sales:", total_sales)
print("Average Sales:", average_sales)

import numpy as np

# Example: Sales data (Rows = Orders, Columns = [Sales, Quantity, Profit])
sales_data = np.array([
    [2500, 10, 200],
    [3000, 15, 350],
    [4000, 20, 500],
    [3500, 18, 400],
    [5000, 25, 800]
])

print("Sales Data:\n", sales_data)

mean_all = np.mean(sales_data, axis=0)
median_all = np.median(sales_data, axis=0)
variance_all = np.var(sales_data, axis=0)
std_all = np.std(sales_data, axis=0)

print("Mean (Sales, Quantity, Profit):", mean_all)
print("Median:", median_all)
print("Variance:", variance_all)
print("Standard Deviation:", std_all)

import numpy as np

# Quantity sold (5 orders)
quantity = np.array([10, 15, 20, 18, 25])

# Unit price per product
unit_price = np.array([250, 200, 180, 220, 300])

import numpy as np

# Sample sales dataset
# Columns: [Quantity, Unit Price, Cost Price]
data = np.array([
    [10, 250, 180],
    [15, 200, 150],
    [20, 180, 120],
    [18, 220, 160],
    [25, 300, 210]
])

quantity = data[:, 0]
unit_price = data[:, 1]
cost_price = data[:, 2]

"""# Task
Convert the 'Price' column of the DataFrame `df` to a NumPy array, and print the first few values of the resulting array.

## Convert Price Column to NumPy Array

### Subtask:
Convert the 'Price' column from the DataFrame `df` into a NumPy array and print the first few values. This demonstrates how to convert additional columns.

**Reasoning**:
The subtask requires converting the 'Price' column from the DataFrame `df` into a NumPy array and printing its first few values. This code block directly addresses that requirement.
"""

sales = [2500, 3000, 4000, 3500, 5000]

total_sales = sum(sales)
average_sales = total_sales / len(sales)

print("Total Sales:", total_sales)
print("Average Sales:", average_sales)

"""**Reasoning**:
The previous step failed because the column 'Price' does not exist in the DataFrame. To fix this, I need to inspect the DataFrame `df` to identify the correct column name that represents price-related information. I will print all column names to find the correct one.


"""

print(df.columns)

"""## Final Task

### Subtask:
Address the missing 'Price' column and ask for further instructions.

## Summary:

### Q&A
The 'Price' column is missing from the DataFrame.

### Data Analysis Key Findings
*   The initial attempt to convert the 'Price' column to a NumPy array failed due to a `KeyError: 'Price'`.
*   Inspection of the DataFrame's columns revealed that the available columns are 'Item Code', 'Item Name', 'Category Code', and 'Category Name'.
*   The DataFrame `df` does not contain a column named 'Price', which was required for the task.

### Insights or Next Steps
*   Further instructions are required on how to proceed, as the 'Price' column, essential for the task, is not present in the current DataFrame.
*   If price data is available from another source, it should be merged into the DataFrame, or a new strategy for obtaining or calculating price should be defined.
"""